### ISSUE TITLE
Feature Request - Class Colour

### ISSUE THREAD

**Issue by jessefogarty** [Matt-Gleich/monovibrant#3]
Love the colour scheme. It's way more vibrant than others I've come across. However, there's two small pitfalls and it's the colour used for the name of classes and type hints.

Classes is pretty straight forward.

But the colour also has a dark navy for types like:
```python
my_var: int = 10
```

**Comment by Matt-Gleich** [comment]
Hey Jesse! I'll look into this sometime in the next week or so :) Glad ya like the theme!

**Comment by Matt-Gleich** [comment]
Hey Jesse! Sorry for the lack of an update here. I am no longer working on this theme. Please check out my [blackbird.vim theme](https://github.com/Matt-Gleich/blackbird.vim).
